import "./globals.css"

import Header from "@/components/header"
import Footer from "@/components/footer"
import Sidebar from "@/components/sidebar"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      {/* <body>
        <main className='min-h-screen bg-background '>
          <div className=' relative grid grid-cols-5 auto-rows-max gap-y-2 '>
            <div className='sticky top-0 self-start row-span-5 col-start-1 row-start-1'>
              <Sidebar />
            </div>
            <div className=' sticky top-0 self-start  z-10 col-span-4 col-start-2 h-fit '>
              <Header />
            </div>
            <div className='col-span-4 row-span-3 col-start-2 row-start-2'>
              {children}
            </div>
            <div className='col-span-4 col-start-2 row-start-5'>
              <Footer />
            </div>
          </div>
        </main>
      </body> */}
      <body className='grid bg-background text-black'>
        <header>
          <Header />
        </header>

        <main className='flex place-self-stretch min-h-screen'>
          <nav className='h-full hidden md:block max-w-screen-sm'>
            <Sidebar />
          </nav>
          <nav className='h-full md:hidden max-w-screen-sm'>
            <div>mobile nav</div>
          </nav>
          <section className='py-16 px-8 w-full'>{children}</section>
        </main>

        <footer className='w-full grid items-stretch'>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
